### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by oyileo** [charnley/rmsd#102]
I try to use it: calculate_rmsd proteinA.pdb proteinB.pdb
but it shows: errors,Structures not same size

**Comment by nbehrnd** [comment]
Hello,

"errors,Structures not same size" indicates a different number of atoms in
structure A vs structure B.  Already a varying presence / absence of hydrogen
atoms attached to the backbone of molecules is one typical cause.

**Comment by charnley** [comment]
As the error message says, you need two molecules of the same size (exact same size and atoms) to align them and calculate a RMSD value. If you think `proteinA.pdb` and `proteinB.pdb` are the same protein/molecule, please re-open the issue and upload the pdb files for me to check.
