### ISSUE TITLE
Calculating hungarian RMSD without alignment

### ISSUE THREAD

**Issue by jgarcianafria** [charnley/rmsd#107]
Hi,

Sorry for the silly question, newbie here. I was wondering whether I could use this program to calculate the hungarian RMSD between two readily aligned molecules (i.e. to calculate RMSD between docked and experimental poses for a ligand). Hence, I would like to calculate the RSMD without prior alignment.

Thank you very much for your help.
Javi

**Comment by charnley** [comment]
I am not sure I understand what you want. You have structures A and B, and you want to calculate the RMSD between the two poses? To me, that sounds like the default calculation.

> Hence, I would like to calculate the RSMD without prior alignment.

I'm not sure I understand what you mean. Can you expand on the example?

**Comment by jgarcianafria** [comment]
Dear Charnley,

thank you very much for your quick reply. I might be not understanding fully and hence the mess. I have exactly what you mentioned, a reference ligand and many docked poses of different ligands. I would like to calculate the RMSD of this poses to the refence molecule. I think I am confused by the "motivation" figure in the "Code" page. In there, there are 3 scenarios, the first one yields an RMSD of 2.5 (unchanged), then a recentered and then a rotated (final 0.25 RMSD). What I am looking for is the first RMSD (unchanged), so I can evaluate how close are the poses of the different docked ligands to the reference ligand. IS this what I can do?

I hope I managed to explain myself.
thank you very much for your help.
Best regards,
Javier

**Comment by charnley** [comment]
Either you want to calculate how much a ligand moved away from it's origin, or you want to compare the two ligands. If you want to calculate the RMSD without doing any transformation (unchanged) then you don't need this package. If you want to compare two structure relatively to each other (transformed and rotated), then you need the default behavior to ensure you compare it correctly. 

This is what I tried to illustrate with the figures in readme.

However, this doesn't seem to be a "issue"/bug and more a discussion on your specific scientific problem, so I will close the issue.
