### ISSUE TITLE
Adding new Features to calculate_rmsd Code

### ISSUE THREAD

**Issue by yazdan12555** [charnley/rmsd#109]
Dear `calculate_rmsd` team, 

Thanks for coding this handy and straightforward RMSD calculator code. I'd suggest that it might be a good idea to add two new features to your AWESOME code:

1- Running the RMSD only on alpha_carbon (CA in the PDB) and/or the backbone atoms (N, CA, C, O).

2- Adding the feature of running RMSD on several PDBs/XYZs by having one of them as the reference, running the code on all at once, and getting all the RMSD values simultaneously. 
I believe the Comp. Chem. and Comp. Biochem. society would highly benefit from these features.

Best,

Yazdan

**Comment by charnley** [comment]
Hello @yazdan12555, You are not the first to request an alpha carbon filter. One note: The PDB format has many edge cases, which is annoying. The alpha carbon argument was added in #114 and will be merged into the master soon.

For feature request 2., no, that is not in scope. I recommend using GNU parallel to do that.
