### ISSUE TITLE
Wrong result for Kabsch RMSD

### ISSUE THREAD

**Issue by cossio** [charnley/rmsd#11]
Try this:

P = [[-1., 0., 0.], [0., 2., 0.], [0., 1., 0.], [0., 1., 1.]]
Q = [[0., -1., -1.], [0., -1., 0.], [0., 0., 0.], [-1., 0., 0.]]

kabsch_rmsd(P, Q)

returns:

1.232398

but the correct least RMSD is:

0.519309

**Comment by larsbratholm** [comment]
I get 0.69 Å when the centroids are subtracted, which is done in the main part of the script, not the kabsch_rmsd function. Can you post the aligned coordinates that results in 0.52 Å?

**Comment by cossio** [comment]
I am using Mathematica (so will use Mathematica notation for convenience). After subtracting centroids the coordinates are:

P = {{-0.75, -1., -0.25}, {0.25, 1., -0.25}, {0.25, 0., -0.25}, {0.25, 0., 0.75}}
Q = {{0.25, -0.5, -0.75}, {0.25, -0.5, 0.25}, {0.25, 0.5, 0.25}, {-0.75, 0.5, 0.25}}

The optimum rotation transforms P into:

rotatedP = {{0.146005, -0.24927, -1.24159}, {0.234296, -0.292242, 0.99232}, {0.297233, 0.16121, 0.103265}, {-0.677535, 0.380302, 0.146005}}

**Comment by larsbratholm** [comment]
Apparently the command you run in Mathematica constructs a mirror plane and inverts P. P and rotatedP does not appear to be the same structure and the 0.69 is most likely correct. Here's P and rotatedP visualized:

http://chemapps.stolaf.edu/jmol/jmol.php?source=http://dl.dropboxusercontent.com/u/17144793/P.xyz
http://chemapps.stolaf.edu/jmol/jmol.php?source=http://dl.dropboxusercontent.com/u/17144793/rotatedP.xyz

**Comment by cossio** [comment]
You're absolutely right. I forgot to check for reflections.
