### ISSUE TITLE
RMSD operation in a numpy array of moelcules

### ISSUE THREAD

**Issue by Megaterium** [charnley/rmsd#30]
I want to calculate RMSD between  A and B, both having the following shape: 

[1000,57,3] where the first dimension correspond to the number of molecules, the second one is the number of atoms and the third one x,y,z positions.

It would be great if it is possible to do this operation without any iteration over the first dimension. I've tried but np.dot(A.T,B) throw an error, so I'm thinking that to accomplish this I'll need to modify the code.

Please let me know your comments.

**Comment by larsbratholm** [comment]
Use x.reshape(57000,3) to make it the right input format?

**Comment by Megaterium** [comment]
I’m currently doing that, but it would be valuable to have element wise RMSD instead of reshaping and “concatenating” all my molecules.

**Comment by Megaterium** [comment]
Thanks for you comment, and sorry for the confusion. I do require in fact RMSD for each molecule.

In my case I have array A which contain 1000 molecules and I need to rotate each molecule and calculate the RMSD against B which also contain 1000 different molecules.

**Comment by andersx** [comment]
Why don't you just make a double loop? I can't see how this is an issue with the RMSD code?
