### ISSUE TITLE
Pip version has slight error

### ISSUE THREAD

**Issue by smcolby** [charnley/rmsd#31]
If installing directly from `pip` (i.e. `pip install rmsd`), running with `--output` does not generate the correct geometry.  It appears the `pip` version is missing the step where `p_all` is translated by `Qc` (Q centroid coordinates):

`pip` version:
```
U = kabsch(P, Q)
p_all -= Pc
p_all = np.dot(p_all, U)
write_coordinates(p_atoms, p_all, title="{} translated".format(args.structure_a))
quit()
```

GitHub version:
```
U = kabsch(P, Q)
p_all -= Pc
p_all = np.dot(p_all, U)
p_all += Qc
write_coordinates(p_atoms, p_all, title="{} translated".format(args.structure_a))
quit()
```

**Comment by charnley** [comment]
You are correct and it is now fixed. New RMSD version is uploaded to pip and automated travis deployment is setup. Hopefully that will make it faster to deploy changes.
