### ISSUE TITLE
Kabsch not zero for same file

### ISSUE THREAD

**Issue by polyluxus** [charnley/rmsd#32]
When using 
```
calculate_rmsd configuration1.xyz configuration1.xyz
```
the result should be 0, since the data sets are identical. However, in case of attached file, they return
```
Normal RMSD: 0.0
Kabsch RMSD: 6.16698752446e-16
Quater RMSD: 0.0
```
Close enough, but why? 

---
Example: 2-bromo-cyclohexan-1-one `conformation1.xyz`
```
17
SCF done       0.00000000
C          0.21071       -0.08068       -1.01215
C         -0.22200        1.24756       -0.37911
C          0.16684        1.30751        1.08071
C         -0.22332        0.10072        1.90828
C          0.16529       -1.20784        1.23556
C         -0.32656       -1.26651       -0.21039
H          1.30419       -0.12448       -1.04911
H         -0.16157       -0.12916       -2.03942
H         -1.30963        1.34512       -0.43942
H          0.22983        2.09315       -0.90165
H          0.22862        0.18105        2.89713
H          1.25813       -1.28534        1.25583
H         -0.24087       -2.04734        1.80504
H         -1.42103       -1.25606       -0.22425
H          0.00821       -2.20042       -0.66980
O          0.74759        2.24101        1.56474
Br        -2.17038        0.22320        2.17266
```

**Comment by andersx** [comment]
They are the same within the numerical precision of your computer. All numerical codes are like this. This is due to how floating point numbers are represented. See e.g.: https://bitbashing.io/comparing-floats.html

Also think about it. Your input coordinates have 5 decimals. Do you really care about 6e-16 difference?

I recommend closing this issue.

**Comment by polyluxus** [comment]
No, I really don't. I found it curious, that the other algorithms give zero, and Kabsch not.  
For all practical intents and purposes I don't have anything to complain about, but maybe rounding to the accuracy supplied with the inputs would still be a good idea.

**Comment by charnley** [comment]
I see your point, however after consideration I don't want to round the number. If users expects more decimals than some hard coded truncation it will just cause confusion.
