### ISSUE TITLE
numpy needs to be installed first, separately, because of rmsd's setup.py structure

### ISSUE THREAD

**Issue by samirelanduk** [charnley/rmsd#33]
Currently the rmsd setup.py has `install_requires=['numpy',]`. In theory this should mean that you can do `pip install rmsd` on a system with no numpy installed, and pip will install both rmsd and numpy.

However currently this is wasted, and trying to do so will throw a `ModuleNotFoundError: No module named 'numpy'`. This is because rmsd's setup.py imports rmsd, which imports numpy, which hasn't been installed yet.

I think this could be fixed by changing `import rmsd` to `from rmsd import __version__`. I can make a pull request if you would prefer.

Otherwise it is currently hard to make rmsd a dependency because then installing *those* projects with pip will fail.

Thanks!

**Comment by larsbratholm** [comment]
The change you proposed didn't seem solve the problem, but I've moved __version__ from the main file to setup.py which seems to work. Thanks for catching this.

**Comment by charnley** [comment]
@samirelanduk, 1.2.7 is now pushed to PyPi via Travis.
