### ISSUE TITLE
Issue with Importing RMSD in Python

### ISSUE THREAD

**Issue by yahtree** [charnley/rmsd#39]
Hello.

Upon installing rmsd, I tried using the functions part of rmsd, as I am working on a script. However, I keep getting the following error message (even when uninstalling/reinstalling):

AttributeError: module 'rmsd' has no attribute 'kabsch_rmsd'

I'd like to know how I can work around this issue. Thanks!

**Comment by larsbratholm** [comment]
You most like have either a file named rmsd.py in your working directory or
are running your script inside the rmsd git repo.

**Comment by charnley** [comment]
@yahtree Can you show the import and use of the rmsd module?

**Comment by charnley** [comment]
inactive issue, closing
