### ISSUE TITLE
infer the two coordinate sets for 3D data

### ISSUE THREAD

**Issue by ahorvath** [charnley/rmsd#40]
Dear Charnley,

How can I infer the fitted coordinates for a pair of 3D datasets?
Beside to the rmsd value, I would like to plot the two dataset next to each other.

Thanks in advance.
Best Regards,
Attila

**Comment by charnley** [comment]
Dear Attila,

I don't understand what you are asking. Are you trying to superpose two molecules on top of each other?

**Comment by ahorvath** [comment]
I'd like to have something like this:

![aligned_objects](https://user-images.githubusercontent.com/351654/46282921-1cce6780-c573-11e8-8c2a-4fad482c5193.png)

Thanks in advance.

**Comment by andersx** [comment]
Put the data points in a dummy XYZ file and pretend they are molecules.

**Comment by andersx** [comment]
Glad it worked!

You can also call the API directly via Python. I think you are looking for something like this:

https://github.com/charnley/rmsd/blob/94b100cdbc4076f2c8eb2ba01a5df9f99ec1f35a/example.py#L52

There is also an example in README.rst
https://github.com/charnley/rmsd/blob/master/README.rst

Subtract the centroids, use rmsd.kabsch() to get the rotation matrix U, and apply it to one of the two coordinate sets.

**Comment by charnley** [comment]
There is also an example here:
https://github.com/charnley/rmsd/blob/master/example.py 

that might be worth looking at. The example is in 2D, but the abstraction is the same.
