### ISSUE TITLE
Function docstrings are a bit confusing about whether centroids are subtracted or not

### ISSUE THREAD

**Issue by smheidrich** [charnley/rmsd#41]
This is a minor nitpick, but in particular the ``kabsch`` docstring is confusing (IMHO) in this respect:
https://github.com/charnley/rmsd/blob/94b100cdbc4076f2c8eb2ba01a5df9f99ec1f35a/rmsd/calculate_rmsd.py#L68-L94
This mentions "a translation of P and Q", but this is not done in the function. So IMO the explanation of the Kabsch algorithm should be put somewhere else or differentiate between what is done in this function and what has to be done by its user, and it should be made clear that these functions (also e.g. ``quaternion_rotate``) compute matrices for rotation around the *origin*, not around the centroids - which is great by the way, because it allows more general use of this library for finding optimal rotations around points other than the centroid.

I'll send a PR if you agree.

**Comment by charnley** [comment]
Hi smheidrich, you are correct, translation is assumed done in that function.

I just pushed my local changes that includes new feature with few documentation changes. If you feel the documentation is not clear or missing, you are very welcome to submit PR with changes to the documentation. 

Nitpicks are welcome :)

**Comment by smheidrich** [comment]
@charnley It's clear now after your changes, thank you very much :)
