### ISSUE TITLE
mirroring / inversion of relative alignments; increment version counter.

### ISSUE THREAD

**Issue by nbehrnd** [charnley/rmsd#42]
As tested today with a *.zip copy obtained Saturday (Nov. 3rd), the implementation of
an optional mirroring and inversion of the test structures nicely automates what
otherwise was performed manually with [aRMSD](https://github.com/nbehrnd/aRMSD).

It really merits to increase the version counter (still today [Nov. 5] at the level 1.2.7, which
was about the state of the art in the second half of September) -- despite your new achievements.

**Comment by charnley** [comment]
As soon as I conclude that the reorder and reflections are bug free I will update the stable release and push the changes to pip. Probably within a week.
