### ISSUE TITLE
Problems with check_reflections function

### ISSUE THREAD

**Issue by share1992** [charnley/rmsd#44]
I know this function is new to rmsd and so might not be fully vetted, but I am having issues with check_reflections. I tested it by using two sets of identical (fake) coordinates, and this function calculates an rmsd between them, as well as suggests reflecting the x-axis. The code I run is:

````
import calculate_rmsd as rmsd
import numpy as np

atoms = ["C","O","O"]
coord1 = np.array([[1.0,1.0,1.0],[2.0,2.0,2.0],[3.0,3.0,3.0]])
coord2 = coord1

atoms=np.array(atoms)

a, b, c, d = rmsd.check_reflections(atoms,atoms,coord1,coord2)
print("min_rmsd = %s" % a, "\nmin_swap = %s" % b, "\nmin_reflection = %s" % c, "\nmin_review = %s" % d)
````

The output is:

min_rmsd = 3.4641016151377526 
min_swap = [0 1 2] 
min_reflection = [-1  1  1] 
min_review = [0 1 2]

Is there something I'm doing wrong in implementing this function, or is it a bug I can't figure out?

**Comment by charnley** [comment]
Hi Stephanie,

It is because the sample `coord1` is not centered around its centroid. It should work if you center it like

    coord1 -= rmsd.centroid(coord1)

Can you confirm that this was the problem?

**Comment by charnley** [comment]
Yes. Actually most (if not all) of the functions assume the structures are re-centered around the centroid. Should probably add explicit comments for that.
