### ISSUE TITLE
partially defunct structure export.

### ISSUE THREAD

**Issue by nbehrnd** [charnley/rmsd#46]
calculate_rmsd.py permits loading of structural models, their superposition, determination of the RMSD and _optional_ export of the second structure -- then aligned to the first one in the *.xyz format.  As I notice, this structure export is affected _badly_ already in the master branch version 1.3.0 (which, to ascertain the situation, was freshly checked-out by mine today); yet equally the [pull request](https://github.com/charnley/rmsd/pull/43) by xg590.  It is observed regardless if *.pdb, or *.xyz data provide the model data to scrutinize once the optional `--p` parameter is used while simultaneously requesting either `--use-reflections`, or `--use-reflections-keep-stereo`.

I became aware of this issue while cross-checking with *.xyz model data derived from crystallographic models about tartaric acid.  Initially, I aimed to check xg590's pull request, the option `--use-reflections` may invert the sterochemical information, which xg590's extension `--use-reflection-keep-stereo` aims to rectify.  The test data for this query are derived from crystallographic models by the Cambridge Crystallographic Database about tartaric acid intentionally simplified to contain nothing but one single molecule of the compound; hydrogens were removed intentionally, too.  For this bug report, only two data sets derived from the entries TARTAC and TARTAC02 are considered, which is about the D-(-)-(2S,3S) isomer among the three possibilities.

After running the computation on the CLI, both the prisitine first model, as well as the second model now described as "aligned" were displayed simultaenously with Jmol.  In the case refraining from any form of `--use-reflection` (no pun intended), the result is well acceptable:

![tartac00-tartac02-noreflectionsatall-master](https://user-images.githubusercontent.com/19709084/50172844-dc6ac400-02ed-11e9-839c-cdf905b0e836.png)

The situation however is bad for  `--use-reflection`  as if the two molecules were solely brought in vicinity of each other only:

![tartac00-tartac02--use-reflections-master-xyz](https://user-images.githubusercontent.com/19709084/50173104-729eea00-02ee-11e9-9af9-756104cfa418.png)

In the attached *.zip archives,  I enclose the raw *.xyz files of the models, the *.xyz exported by calculate_rmsd.py along `python calculate_rmsd.py --reorder -p [--use-reflection] modelA modelB`, as well as *.png screen photo and *.wrl export of the screne (accessible e.g. by [view3dscene](https://packages.debian.org/sid/main/view3dscene) in Debian) of two runs with the current master branch version 1.3.0 of the script.

It is noteworthy that the test on _these_ models is not affected if the script is used with or without the optional parameter of `--use-reflection` or `--use-reflections-keep-stereo` (RMSD about 0.098) because they represent the same stereoisomer.

[sameIsomer-noReflectionsAtAll-master.zip](https://github.com/charnley/rmsd/files/2691694/sameIsomer-noReflectionsAtAll-master.zip)
[sameIsomer--use-reflections-master.zip](https://github.com/charnley/rmsd/files/2691695/sameIsomer--use-reflections-master.zip)

**Comment by nbehrnd** [comment]
In addition to the previous bugreport, I add below documentation about using the same model data with the script currently filed under "pull request".  Again, the zip-archive includes the model data and the script used, intermediate outputs obtained, and Jmol's exports as static *.png and potentially interactive vrml *.wrl.

The superposition in the default mode, in a pattern like

`python calculate_rmsd.py --reorder -p modelA modelB`

looks like:
![tartac00-tartac02-newscript-default](https://user-images.githubusercontent.com/19709084/50237848-ccb6b280-03b5-11e9-9039-84dd62ee19f5.png)

The superposition in the pattern of 

`python calculate_rmsd.py --reorder --use-reflections -p modelA modelB`

looks like:
![tartac00-tartac02-newscript-reflection](https://user-images.githubusercontent.com/19709084/50237950-1a331f80-03b6-11e9-9b0a-18a3dda220a4.png)

Eventually, the deemed to be more (stereoconservative) approach by

`python calculate_rmsd.py --reorder --use-reflections-keep-stereo -p modelA modelB`

equally looks like:

![tartac00-tartac02-newscript-reflectionkeepstereo](https://user-images.githubusercontent.com/19709084/50238023-4353b000-03b6-11e9-8a5c-5f1e152d4c0d.png)

[xvalidation-tartaricAcids-DKCHNYC-bugreport-20181219.zip](https://github.com/charnley/rmsd/files/2695960/xvalidation-tartaricAcids-DKCHNYC-bugreport-20181219.zip)

**Comment by charnley** [comment]
The error originated from the rotation calculated before the reordering when printing the structure. Has been corrected.
