### ISSUE TITLE
Reordering two differently sized but similar molecules

### ISSUE THREAD

**Issue by JonKragskow** [charnley/rmsd#50]
I'm trying to reorder two differently sized molecules so that they share as much of the atom numbering in common. I seen you've got this feature for molecules of the same size which is brilliant, but how could I go about comparing two differently sized molecules? Any help would be very appreciated!

Cheers, 

Jon

**Comment by charnley** [comment]
Dear Jon,

Can you describe a little more on why and what exactly you want to compare?

I'm guessing you want to calculate some sort of similarity between two different molecules? This is a very interesting question, but not one root-mean-square-deviation of atomic positions can solve, as RMSD requires exactly what the system cannot deliver 1) same number of atoms in 2) the same order.

If what you are interested in simply "is this molecule similar to this other molecule" then I highly recommend looking into the field of machine learning on chemistry (this is what my current research group is focusing on), and in particular the field of "kernel ridge regression" methods. From these models you calculate a "kernel" between two representation of molecules, to create a similarity matrix (kernel matrix) for multiple molecules. 

Kernel ridge regression is a ML method for predicting properties of molecules, but the theory/representations behind it can be used to solve your molecule similarity problem. We are currently also using this approach to compare conformers, where the RMSD approach is lacking.

You can read about the theory and approach here
http://www.qmlcode.org/tutorial.html
http://www.qmlcode.org/examples.html
https://github.com/qmlcode/qml

**Comment by JonKragskow** [comment]
Dear Jimmy,

Many thanks for taking the time to reply.

The problem stems from comparing the vibrational modes of two different coordination complexes. For me, the difference in the complexes lies in the substitutions of the ligands - in this case substitution of the cyclopentadienyl rings. The process of comparing the vibrational modes requires the atoms in each molecule to be listed in a similar order - that is all of the common atoms are given the same index number. For example one might consider comparing ethane and butane - there are atoms which are common to both and some which are unique to butane. I'm trying to automate the process of renumbering the atoms such that the atoms common to the two molecules are indexed the same, with the remaining unique atoms numbered in sequence after the common ones.

The reason for me asking this question is because of the implementation of reordering in calculate_rmsd

I did think this would be something machine learning could help with! I'll take a look at the links you have provided.

Thanks!

Jon

**Comment by charnley** [comment]
For that I would suggest using rdkit http://www.rdkit.org/docs/GettingStartedInPython.html and try to map one molecule onto another using substructure searching. Maybe a combination of rmsd reorder and rdkit can solve it. Either way, I would say mapping atoms on different molecules is a non-trivial problem.
