### ISSUE TITLE
multiprocessing with calculate_rmsd.py

### ISSUE THREAD

**Issue by nbehrnd** [charnley/rmsd#51]
Interested to deploy calculate_rmsd.py in a series of comparisons with
"true clusters" (cf. _vide infra_) my intent was to deploy calculate_rmsd.py
with a moderator script.  For smaller tests (one molecule A ./. one molecule
B), using a linear approach was fast enough.  Now facing larger clusters,
the thought occured to me that the mere testing then could be performed
in parallel, on multiple CPU cores.  My call of module multiprocessing,
however, yields a situation where each CPU seems to see the list of iterable
tests to perform as its own, to the extent that each core engaged performs
the task -- even if an other core determined RMSD already.

Question:  Does an other user of calculate_rmsd.py has experience to
parallelize the script?  Is there a keyword I did not spot yet to organize the
computation within this loop?

Disclaimer : because it is the first time that I search for a more parallelized
approach, possibly other approaches than the multiprocessing module may
work.  The intent is to run scrutinies with files like the attached ones for series
of 50...150 test clusters each, with about a dozen of molecules per cluster,
edited such that the scipt may work with them.  Rapidly, this will increase the
computational cost (i.e., n * (n-1)/2 tests per n clusters).  Suggestions may
be helpful to related issues such as deposit [here](https://github.com/charnley/rmsd/issues/35), too.

[simplifiedModerator.py.txt](https://github.com/charnley/rmsd/files/3008343/simplifiedModerator.py.txt)
[modelData.zip](https://github.com/charnley/rmsd/files/3008345/modelData.zip)

**Comment by nbehrnd** [comment]
After many tests one way to distribute the computational load onto
multiple CPU cores was found which seems to be good enough to provide
some of acceleration sought.  If called in presence of calculate_rmsd.py,
typically the work with additional processors starts after the first test pair
of models was scrutinized.  A little bemol occurs when the script closes --
at least while running Python 3.6.7 -- stating an assertion error, possibly
something an advanced Pythonista may find a correction.

[polyCPU-moderator.py.txt](https://github.com/charnley/rmsd/files/3013594/polyCPU-moderator.py.txt)

**Comment by nbehrnd** [comment]
The use of a ProcessPoolExecutor provided with module concurrent,
replacing multiprocessing's approach offers a solution without ocurrence
of an assertion error.
[multipro.py.txt](https://github.com/charnley/rmsd/files/3014269/multipro.py.txt)

**Comment by nbehrnd** [comment]
As tested with a tiny set of five model data (each with about a dozen of molecules
per cluster file), the problem seems to be fixed by a moderator script deposit [here](https://github.com/nbehrnd/rmsdModerator).

**Comment by charnley** [comment]
@nbehrnd , reading through your code you definitely should use rmsd as a module/package. From your code you can `import calculate_rmsd as rmsd` and use the functions. And not call it with subprocess command.
