### ISSUE TITLE
feature suggest: output of *.xyz .AND. RMSD

### ISSUE THREAD

**Issue by nbehrnd** [charnley/rmsd#52]
I would like to suggest, as additional option, output of the aligned
structure B, in *.xyz format, and RMSD in one step.
For the scrutiny of larger clusters taking longer time to scrutinize,
and with the issue of single-core computation pending, this may
cut the computational time to spend by half.

My understanding of the argparse-defining section (lines #795
following) is too little to achive this by addition of line like 
 `parser.add_argument('P', action='store_true', help='print out structure B,  after refined fit in XYZ format and provide RMSD'`
(lead by upper case P), tentatively placed on line #1040 and
followed by an (edit) copy-paste of section line #999 till and
including line #1039.

What worked for me as short-cut is the copy-paste of line #1036 just
after line #1023 to obtain a permanent record of RMSD with
the corresponding alignment which however works only when either
`--use-reflections -p`
or
`--use-reflections-keep-stereo -p`
is used.  The numeric value of RMSD however is the same as when
calling calculate_rmsd.py without `--use-reflections` or `--use-reflections-keep-stereo`
without the optional `-p` parameter.  Perhaps I missed an entry
corresponding to filename of either fileA, and fileB easing the
generation of a permanent record of aligned molecule B if the
script is called within a loop, but may harvest both types of
information from the CLI piped output /via/ grep.

The attached *.txt is the slightly modfified script, rather as source of
inspiration than as commit.
[20190326-modified-calculate_rmsd.py.txt](https://github.com/charnley/rmsd/files/3009365/20190326-modified-calculate_rmsd.py.txt)

**Comment by nbehrnd** [comment]
A possible implementation, working if calling `calculate_rmsd.py` altogether with
the optional parameters of either `--use-reflections -p` or `--use-reflections-keep-stereo -p`
in a batch-wise scrutiny on multiple CPU cores was deposit as pull request [here](https://github.com/charnley/rmsd/pull/54).

**Comment by charnley** [comment]
I leave multiprocessing implementations of rmsd to usage as a module by the user.
