### ISSUE TITLE
Reorder with Hungarian and distance gives larger RMSD

### ISSUE THREAD

**Issue by hmcezar** [charnley/rmsd#61]
I'm noticing some strange behavior when using the reorder option.
Sometimes, the RMSD after reordering is larger than without reordering.

For example, for the two structures below:
[hmcezar@bitz-dell teste]$ calculate_rmsd 47.xyz 48.xyz 
1.670565405538033
[hmcezar@bitz-dell teste]$ calculate_rmsd 47.xyz 48.xyz -e
4.956142899937815

Is this an expected behavior?

The .xyz files are at [https://pastebin.com/4srhWypu](https://pastebin.com/4srhWypu).

**Comment by charnley** [comment]
Hi hmcezar,

Unfortunately, yes, it is expected. If the molecule is translated/rotated in an unfortunate position, the distance cost used for the Hungarian algorithm will be misleading and produce wrong atom orders. One fix I'm working on (when I find the time) is to first align the atoms along the axis of inertia, as this will give a better atom-atom distance calculation.

Another potential fix is to use "chemical similarity" and use kernel similarity for the Hungarian cost function. I recently did this implementation and can be found on the qml branch. Usage is quite simply (i tried it on your xyz files);

    $ python3 calculate_rmsd.py test_hmcezar/mol_{a,b}.xyz -e --reorder-method qml
    0.7180215941806747

For it to work you'll need the development branch of `qml`

    pip3 install git+https://github.com/qmlcode/qml@develop --user -U

and the qml branch of `rmsd`

    git clone -b qml https://github.com/charnley/rmsd

Let me know if that solves your problem.

**Comment by hmcezar** [comment]
Hi charnley,

Thank you very much for your response.
Indeed, this is the exact behaviour that I expected for my application.
Looks like I'll have to add another dependency.

Concerning your comment of aligning the axis of inertia before solving the assignment, wouldn't it be equivalent of applying the Kabsch rotation, and then doing the reordering?
I'll play a bit with this and come back with a possible solution when I have the time.

Thanks again!

**Comment by charnley** [comment]
To do a Kabsch rotation, you need to have the correct atom ordering, so aligning inertia is more of a "good guess" for the atom-atom distances used in the Hungarian algorithm. Even with an initial inertia alignment, I think chemical similarities will give a better assignment.

Another approach would be to calculate the molecule graph and compare that. At this moment, I think the most effortless approach will be using the `qml` reordering. I know others have used "molecule fingerprints" of the graph for assignment.

If you want to just overwrite `calculate_rmsd` command you can also just run the following commands;

    pip3 install git+https://github.com/qmlcode/qml@develop --user -U
    pip3 install git+https://github.com/charnley/rmsd@qml --user -U

and then

    calculate_rmsd -e --reorder-method qml 47.xyz 48.xyz

I have not tested it for large molecules/proteins, though, that might be computationally expensive and difficult to assign.

**Comment by hmcezar** [comment]
I've submitted a pull request with the implementation of the aligned inertia.
The only problem that I've come across during the early stages of testing, is that sometimes, the structures were antiparallel after the alignment of the axis.

I'm not sure my implementation is the best idea, but what I'm doing is assuming that it can be either parallel or antiparallel for testing, but returning just the smallest RMSD.
I don't know if there's another way to make sure that the alignment is not antiparallel.

**Comment by charnley** [comment]
Looks great. However, the principal inertia axis alone will still give a guess that in some cases will give atom-atom distances that the Hungarian algorithm will assign wrongly, not only anti-parallel but also rotationally around the axis. I've been working on a fix for this, might be pushed next month though (needs some rigid testing) and I didn't priorities it since the `qml` assignment works quite well.

**Comment by charnley** [comment]
Inertia alignment and qml has been added to the master branch, which addresses this issue. So I will close the issue.

https://github.com/charnley/rmsd/blob/master/tests/test_reorder_qml.py
https://github.com/charnley/rmsd/blob/master/tests/test_reorder_inertia.py
