### ISSUE TITLE
reading .xyz files doesn't work when they contain scientific notation

### ISSUE THREAD

**Issue by puckvg** [charnley/rmsd#63]
for example, this file, 

19

C	-2.293946	-3e-06	-0.156296
C	-1.072129	0.756112	-0.6106
C	-1.072122	-0.756104	-0.610611
C	-0.06715	-1.123802	0.475015
C	1.358616	-1.188877	-0.086502
O	1.677474	3e-06	-0.799713
C	1.358611	1.18888	-0.086499
C	-0.067151	1.123797	0.475026
O	-0.11043	-8e-06	1.371348
H	-2.543398	-1.2e-05	0.89919
H	-3.143761	-8e-06	-0.829798
H	-1.086381	1.326009	-1.5315
H	-1.086375	-1.325977	-1.531525
H	-0.309135	-2.019187	1.056162
H	2.055688	-1.340367	0.752686
H	1.481047	-2.012895	-0.797179
H	2.055691	1.340376	0.752679
H	1.481026	2.012901	-0.797177
H	-0.309129	2.019175	1.056186

gives the error message,
`Reading the .xyz file failed in line 2. Please check the format.`

**Comment by nbehrnd** [comment]
Well, there are more than one instance containing the `e` and 10E-6 Angstroms is very close to zero.

[openbabel](http://openbabel.org/wiki/Main_Page) may provide you a quick help here.  The program, which may both read and write `.xyz` files, is freely available for Linux, Windows, or Mac, either for use from the command line / terminal, or with a GUI on top.

Here is what I did: In a first step, the snippet provided by you was pasted into an editor, saving as `test.xyz`.  Then, entering the corresponding folder containing said file from the CLI, the command was

`babel -ixyz test.xyz -oxyz reformat.xyz`

to yield the sanitized file `reformat.xyz`.  As you may see from the screen photo, babel equally adjusts a little the columns, too.  In case you have multiple `.xyz` files which _potentially_ contain the same issue as the example provided by you, it may be helpful to script babel's action (e.g., Python) to automate this task and improve consistency of the data to work further.

[test.xyz.txt](https://github.com/charnley/rmsd/files/4136286/test.xyz.txt)
[reformat.xyz.txt](https://github.com/charnley/rmsd/files/4136287/reformat.xyz.txt)
![sanitized](https://user-images.githubusercontent.com/19709084/73491249-784e7680-43ae-11ea-9609-148201987d18.png)

**Comment by charnley** [comment]
Problem was regex was reading `3.0e3` fine, but not `3e3`. A fix using `.split` has been added. Will update regex to be more general and add some unit testing for xyz-line reading in the near future. Fixed in ce7f5334056874689f89eb4ee6e24085b5e5f749
