### ISSUE TITLE
How to calculate rotation matrix using rmsd?

### ISSUE THREAD

**Issue by Z-Jeff** [charnley/rmsd#69]
How to calculate the rotation matrix between two set paired sets of points using rmsd?

**Comment by nbehrnd** [comment]
While this thought did not occur to mine earlier, I welcome and
support the suggestion to add an optional report of the
transformation matrix.

Aside from «reproducible research» for working with
'calculate_rmsd.py' with either Kabsch algorithm, or quarternion
approach, there are other programs in search for a best fit of two
structures superimposed (e.g., PyMol, CrystalCMP allow to work with
batches of structures; aRMSD restrains to a one-by-one basis). Here,
the optional report of the transformation matrix were of diagnostic
value, complementary to the measure «... and what is the remaining
difference between the two?» already provided.

**Comment by andersx** [comment]
```python
# Center geometries
query_centroid -= np.mean(query_geometry, axis=0)
reference_centroid -= np.mean(reference_geometry, axis=0)

# Get rotation matrix
U = rmsd.kabsch(query_geometry, reference_geometry)
```

**Comment by charnley** [comment]
@Z-Jeff did that answer your question?
