### ISSUE TITLE
How to align both position and orientation?

### ISSUE THREAD

**Issue by marekyggdrasil** [charnley/rmsd#71]
Thanks for great library! It looks like just what I was looking for apart from one thing and I was wondering if someone could leave some comments.

I have two sets, P and Q. Elements of P correspond to elements of Q. Each element has a set of three coordinates in the 3D space and also orientation coordinates (which can be expressed using Euler angles, quaternions, rotational matrix, anything that is most convenient). How to align P and Q?

According to the [Quaternion Algorithm paper [2]](http://dx.doi.org/10.1016/1049-9660(91)90036-o) cited in the README, both position and orientation are getting aligned. Quoting from the abstract

> This paper describes a new algorithm for estimating the position and orientation of objects (...)

However, when I look up the tests I see that even with both positions and orientations available, only the position coordinates are taken into account

https://github.com/charnley/rmsd/blob/55eebc390458307c548b45adfeb84d9f194c4344/tests/test_quaternion.py#L24

I think I might have misunderstood something. Was the the orientation alignment purposely skipped (as it might not be relevant to the usual use-case). Could someone recommend how to solve my problem? Perhaps different algorithm would be more appropriate.

Many thanks in advance!

**Comment by charnley** [comment]
If I understand your question correctly, you have elements P as a subset of Q? If so you'll need to align P and Q only on the matching elements. 

- Select the overlap coordinates between P and Q
- Re-center P and Q to (0,0,0) so the centres are on top of each other. Keep the original centres. `rmsd.centroid() `
- If coordinates are not in the same order, you'll need to re-order the atoms/elements `rmsd.reorder_*`. Many to choose from. 
- Calculate the rotation matrix between P and Q, and apply it to P `rmsd.kabsch()` 
- Then add the center off-set from Q to P

the result is you now have P and Q aligned, on the elements they overlap.

Did that answer your question? If not, can you give me an explicit example, 2D or 3D.

**Comment by marekyggdrasil** [comment]
Thank you for such quick answer @charnley ! Unfortunately this is not exactly what I needed... It is a good idea to prepare an explicit example, let me think about it for a while and I will post it here. It will have explicit points and orientation coordinates.

**Comment by marekyggdrasil** [comment]
@charnley I came up with a little example.

Let us consider a 3D space with `N=5` points `{a, b, c, d, e}`. We are provided with two noisy snapshots of this space, the `P` set has all `5` points and `Q` set only has `4` points as it is missing point `a`.

P set
![P_set](https://user-images.githubusercontent.com/8202674/108670131-5247c700-7519-11eb-8354-fa6c140179f3.png)
[positions in JSON format](https://gist.github.com/marekyggdrasil/d53962355a47eb975b4b7650b05c7fba#file-data_p-json)

Q set
![q_set](https://user-images.githubusercontent.com/8202674/108670148-583da800-7519-11eb-8ae2-43d40fe1bd80.png)
[positions in JSON format](https://gist.github.com/marekyggdrasil/d53962355a47eb975b4b7650b05c7fba#file-data_q-json)

Each of the points in each set has 3 spatial coordinates as well as a rotation vector indicating its orientation. On the visualized figures they are represented using colored spheres. The white sphere is representing the origin of the coordinates.

Example data is generated as follows.

1. Generate `N=5` points with random positions and random orientations
2. For each of the point sets `{P, Q}` take a copy of that space, apply some small noise for the position and orientation, scale by a scalar and randomly shift origin
3. Remove point `{a}` from set `Q`

The generation algorithm is provided [here](https://gist.github.com/marekyggdrasil/d53962355a47eb975b4b7650b05c7fba#file-gen-py-L9-L35).

Problem: Find a way to overlap set `P` on top of `Q` in a way such that positions (and orientations!!!) match as closely as possible. Note that point `Q` is missing one point `{a}` so the position of that point from set `P` would have to shift where it point would be expected based on translation of remaining points which do have their matching counterpart in `Q`.

Context: I am working on algorithm that is using computer vision to reconstruct a 3D pose based on many photos with identified markers. I want to translate and rotate photos (with possibly missing markers) to overlap as closely as possible in order to average out the errors. Position averaging is pretty simple, however noise in orientations I intend to average out using [averaging quaternions algorithm](https://github.com/christophhagen/averaging-quaternions).

Is this a bit more clear? I will be happy to detail it even further.

**Comment by charnley** [comment]
Hi @marekyggdrasil, I got it. There is no way for the module to take into account the orientations of the points, as Kabsch is minimizing the rotation matrix for distances between points.

A hack you can do is to add displacements points around your point that follows the orientation, so the points becomes a vector. You'll still need to the same order of points, in the right order to probably rotate the points.

However, aligning points with different orientations is currently out-of-scope for this package.

**Comment by marekyggdrasil** [comment]
Thanks for the feedback @charnley . I think now I am starting to understand how the Kabsch works. Since it is minimizing the rotation matrix I think it should still apply for the orientations automatically. Reason for that is that is the following analogy.

Let R be an optimized rotation which is minimizing the distances between the corresponding points. Suppose each of the points has an orientation. If we displace points by rotating them by R about the displaced origin their respective orientations should also be rotated by R. Not a very formal proof, but intuitively we can imagine they get shifted to their origin, rotated by R and then displaced back in the direction indicated by their displacement vector.

Thanks again!
