### ISSUE TITLE
Pre-specify residuals?

### ISSUE THREAD

**Issue by proteneer** [charnley/rmsd#74]
I'm looking for a method that lets me specify a list of distances to minimize the RMSD against. i.e.  Given two point clouds each with size N, and a 1-1 correspondence, as opposed to having the distances be as close to zero as possible between each pair, have it instead be as close to some distance k_i (varying for each pair).

**Comment by andersx** [comment]
Minimize with respect to what DOFs?

**Comment by proteneer** [comment]
Minimize with respect to the translation and rotation.

**Comment by andersx** [comment]
That is what this function does:
https://github.com/charnley/rmsd/blob/55eebc390458307c548b45adfeb84d9f194c4344/rmsd/calculate_rmsd.py#L416

**Comment by charnley** [comment]
Closing issue because of stale/missing information. If still an issue please re-open.
