### ISSUE TITLE
error: Structures not same size

### ISSUE THREAD

**Issue by raji-pixel** [charnley/rmsd#88]
HELLO,

I would like to calculate the rmsd beween native and redocked ligand.

 `calculate_rmsd --reorder native.pdb redocked.pdb`

[native.txt](https://github.com/charnley/rmsd/files/8792905/native.txt)
[redocked.txt](https://github.com/charnley/rmsd/files/8792906/redocked.txt)

`error: Structures not same size`

The number of atoms in both files are same. Could you please help me to solve this simple error?

**Comment by nbehrnd** [comment]
There is an issue with how the data are reported.  If you read the two files e.g., in [jmol](http://jmol.sourceforge.net/) and visualize the two structures side-by-side, the more obvious issue (_vide infra_) is about the chlorine once recognized _as such_, once as carbon:

![synoptic](https://user-images.githubusercontent.com/19709084/170867155-fa8933c7-128e-4ffe-92fc-21ee8cffabc1.png)

---

Contrary to anticipation, the conversion in simple `.xyz` files with [openbabel](https://github.com/openbabel/openbabel) in a pattern like

```bash
$ obabel -isdf native.txt -O native.xyz
```
did not yield consistent results:

```bash
$ obabel -ipdb redocked.txt -oxyz
18
redocked.txt
*         43.24700      -18.29500       20.36900
C         43.44700      -16.54000       20.42100
*         42.95900      -18.96800       21.57100
*         42.79300      -20.34800       21.57300
*         42.92000      -21.02400       20.35600
N         42.81400      -22.36100       20.05500
*         43.03100      -22.55600       18.69500
*         43.27800      -21.34100       18.09400
*         43.21300      -20.34900       19.13900
*         43.37800      -18.95300       19.15600
C         43.51000      -21.05600       16.63500
C         44.46200      -22.02000       15.90900
C         43.94500      -23.45800       15.74500
C         43.91900      -24.30800       17.02500
C         42.90900      -23.95500       18.14500
C         41.46200      -24.27100       17.78800
N         40.58200      -23.35400       17.79700
O         41.28400      -25.58600       17.46700
1 molecule converted
```
As an intermediate curation, _all atoms_ (in both `.xyz`) were treated like carbon.  _Per se_, the subsequent 

```bash
$ calculate_rmsd native.xyz redocked.xyz 
3.4865071842513533
```
worked well; yet now does not account for the rotation of the amide (cf. _vide supra_, the less obvious issue).

Maybe the docking program you use offers an adjustment of the `.pdb` written; if bond orders are not of your concern, perhaps an export of the structures as `.xyz` (a format `calculate_rmsd.py` equally accepts as an input) might be an option.

[reformatted_data.zip](https://github.com/charnley/rmsd/files/8793327/reformatted_data.zip)

**Comment by charnley** [comment]
Hi @raji-pixel, the PDB reader has never been the strong side of this codebase. There are always edgecases. In this case, it is because the atoms are described as HETATM instead of ATOM, so the simple PDB parser does not read any atoms. I will open a pull-request and add HETATM as a keyword to parse.

Until then I recommend using `sed` to rename all `HETATM` to `ATOM`.

**Comment by charnley** [comment]
@raji-pixel Fix has been merged to master. Please try again with the updated code and open the ticket if there are any issues.
