### ISSUE TITLE
error: Structures not same size

### ISSUE THREAD

**Issue by mns-csharp** [charnley/rmsd#92]
I used `pd2_ca2main` to generate a PDB file.
I am trying to compare the new file with the old one, but I can't.

```
user_name@server_name:~/bbq_spatial$ python3 calculate_rmsd.py  ./bbq_input_pdb/pdb1akp.pdb  ./bbq_output_pdb/pdb1akp.pdb
error: Structures not same size
user_name@server_name:~/bbq_spatial$

```

**Comment by charnley** [comment]
I need more details. 

The error you are getting means that there is not the same number of atoms the two pdb files.

Is `pd2_ca2main` only changing the coordinates? Or does it remove Hydrogens?

**Comment by mns-csharp** [comment]
pd2_ca2main  is a tool, or rather an algorithm, that reconstructs the main chain from its C-alpha backbone only. It actually adds hydrogen to a C-alpha backbone. However, the newly constructed PDB file contains many duplicate atoms.

**Comment by charnley** [comment]
> However, the newly constructed PDB file contains many duplicate atoms.
That is not something the rmsd tool can figure out. You'll need to remove all duplicates so there is a 1:1 match of atoms for alignment.

**Comment by mns-csharp** [comment]
A duplicate atom means an alternative coordinate.
A PDB file containing alternative coordinates is very standard, I think.
