### ISSUE TITLE
rmsd package requires typing_extensions but missing from setup.py

### ISSUE THREAD

**Issue by epeisach** [charnley/rmsd#95]
Create a new virtual environment:

% python3 -m venv /tmp/v3
% source /tmp/v3/bin/activate
(v3) % pip install rmsd
Collecting rmsd
  Using cached rmsd-1.5.0-py3-none-any.whl (17 kB)
Collecting scipy
  Using cached scipy-1.9.3-cp310-cp310-macosx_10_9_x86_64.whl (34.3 MB)
Collecting numpy
  Using cached numpy-1.24.0-cp310-cp310-macosx_10_9_x86_64.whl (19.8 MB)
Installing collected packages: numpy, scipy, rmsd
Successfully installed numpy-1.24.0 rmsd-1.5.0 scipy-1.9.3

 % python3
Python 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rmsd.calculate_rmsd import (NAMES_ELEMENT, centroid, check_reflections, rmsd)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/v3/lib/python3.10/site-packages/rmsd/__init__.py", line 2, in <module>
    from .calculate_rmsd import *
  File "/private/tmp/v3/lib/python3.10/site-packages/rmsd/calculate_rmsd.py", line 25, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by charnley** [comment]
Better typing control (removed typing_extension) and dropped support for Python 3.7.
