### ISSUE TITLE
Willing to add the rmsd value to title line?

### ISSUE THREAD

**Issue by rafaelpap** [charnley/rmsd#97]
Sometimes I am interested in knowing the rmsd value for the modified structure. Now I need to run calculate_rmsd.py twice (with and without -p).
With this simple change the rmsd value is printed in the title line of the xyz file.

line 2052 from:
xyz = set_coordinates(q_all_atoms, q_coord, title=f"{settings.structure_b} - modified")
to
xyz = set_coordinates(q_all_atoms, q_coord, title=f"{settings.structure_b} - modified. RMSD = {result_rmsd}")

**Comment by charnley** [comment]
Added in #112
