### ISSUE TITLE
Why these two pdbs can not calculate RMSD?

### ISSUE THREAD

**Issue by Qmi3** [charnley/rmsd#98]
The first file contain hydrogen but when i use --no-hydrogen and --reorder ,it's still reported that structure not same size .They are both 169 residues.

**Comment by Qmi3** [comment]
[test.txt](https://github.com/charnley/rmsd/files/10964787/test.txt)
[test1.txt](https://github.com/charnley/rmsd/files/10964788/test1.txt)

**Comment by charnley** [comment]
Hi @Qmi3 , interesting problem. So other than Hydrogens, one file also included the rest of the amino acids, whereas the other only included the core. The same number of amino acids, different number of atoms.

I opened up a branch https://github.com/charnley/rmsd/tree/charnley/issue-98 to try to resolve this. I have added a new argument to only look at the alpha Carbons of a protein structure. This is extremely hard to reorder though! But it seems your structures were already ordered.

Please try it out and let me know if this solves your issue.

**Comment by andersx** [comment]
You can use Pymol for this

**Comment by charnley** [comment]
It will be covered with PR #115. You can now compare structures that are not the same but only compare the alpha carbons.
